version: '3'

volumes:
  transmission_data:

networks:
  frontend:

services:

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Yekaterinburg
      - USER=${transmission_user}
      - PASS=${transmission_pass}
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - transmission_data:/config
      - /mnt/data:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - fronted
