---
- hosts: all

  tasks:
    - name: Create network
      community.docker.docker_network:
        name: frontend

    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_date:/data
        networks:
          - name: frontend
        restart_policy: always

    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        command: --schedule "0 0 4 * * *"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - name: frontend
        restart_policy: always
